### ISSUE TITLE
POPSLoader clarification in features list

### ISSUE THREAD

**Issue by eighthdayregret** [PSP-Archive/ARK-4#180]
### New Feature

The features list states that POPSLoader is compatible with ARK, but does not specify that the feature only applies to the PSP, and does not work on the Vita. There is no mention anywhere on the GitHub for ARK that explains this, and is therefore misleading.

**Comment by JoseAaronLopezGarcia** [comment]
Two thoughts about this:

- The readme clearly states "Popsloader V3 and V4i", it specifies exactly which versions of popsloader are supported, and these versions are clearly known to not work on PS Vita.
- The CFW itself IS compatible with a theoretical Popsloader on PS Vita (and so is Adrenaline). It's not the fault of the CFW that such plugin doesn't exist, but compatiblity IS there. The functionality that the CFW has to implement to allow Popsloader is there, fully implemented and fully functional, there simply is no plugin to use it.
- Rather than doing any clarifications on the Readme, I would rather cleanup the readme and work towards the Wiki, which should allow us to have more flexibility when it comes to documenting and explaining.
