### ISSUE TITLE
Update dialog

### ISSUE THREAD

**Issue by Kitki30** [PSP-Archive/ARK-4#257]
### New Feature

Show update dialog when its available and psp is connected (in VSH Menu style or better in launcher)

**Comment by JoseAaronLopezGarcia** [comment]
We can't do this for various reasons, mainly because it would require having WLAN turned on at all times which would drain the battery very fast, but also because people using the /test update server (like myself) will be constantly told to update since that server always reports a new update available even if there isn't, this would be very anoying.
