### ISSUE TITLE
what happened to the old recovery meenu

### ISSUE THREAD

**Issue by Xtremegamer13579** [PSP-Archive/ARK-4#410]
### PSP/Vita Model

PSP-2000 (Slim)

### ARK Version

4.40.69 r15

### Steps to reproduce

Please bring back the old recovery menu

### USB Charge

Always

### Overclock

Always

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Always

### Inferno Cache

LRU

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

Off

### Hide MAC Address

On

### Hide DLC

Off

### Turn off LEDs

Disabled

### Verification of form.

- [X] I agree that I properly filled out the items listed above.

**Comment by Xtremegamer13579** [comment]
![Uploading unnamed (2).jpg…]()

**Comment by Xtremegamer13579** [comment]
![Uploading unnamed (1).jpg…]()

**Comment by Xtremegamer13579** [comment]
![unnamed](https://github.com/user-attachments/assets/6b80ea8c-7a1a-4213-ba85-bcf0eed9ea7a)

**Comment by Xtremegamer13579** [comment]
![unnamed (1)](https://github.com/user-attachments/assets/8c496924-eb65-420c-886a-b2f8d5a1f17d)

**Comment by Xtremegamer13579** [comment]
![unnamed (2)](https://github.com/user-attachments/assets/2fad3b90-9518-4309-8120-3ef1245d92ea)

**Comment by krazynez** [comment]
We choose to use the classic Recovery menu over the similar to Custom Launcher (CL) style one, because it can fit in flash and run like older CFW, and was a bit of a pain duplicating things for both menus. This way it actually separates them and Recovery is not dependent on CL. 

Also this would be more of a question in the discord not and issue on github. :+1:

**Comment by JoseAaronLopezGarcia** [comment]
The old recovery menu was merged with the custom launcher, you can still use it by loading the custom launcher and holding the R button as soon as the launcher starts up.
This was done for several reasons:
- It reduces redundancy (there was already too many recovery options).
- It adds recovery options to the CL itself.

The old recovery menu was already just a stripped down custom launcher.

In any case, if you really really really want it back, you can download an old ARK version that still has RECOVERY.PBP and copy it over to the latest version, since we only really deleted the file, we never took away the code that allows you to use it. You can technically use whatever homebrew you want for RECOVERY.PBP so that's nice.

**Comment by Xtremegamer13579** [comment]
There is another problem I have which that when ever i use the update file to update ark 4 it boots the file then after a few seconds the psp switches off
________________________________
